version: '3.9'
services:
  nginx:
    image: nginx:latest
    ports:
      - 9999:80
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/html
  db:
    image: mariadb:10.6
    container_name: maria
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "bqY9pNv*33f"
      MYSQL_DATABASE: "mariadb"
    ports:
      - 3306:3306
    networks:
      - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    networks:
      - database
    environment:
      PMA_HOST: "172.19.0.2"
      PMA_PORT: "3306"
      PMA_ARBITRARY: "1"
    restart: unless-stopped
    ports:
      - 8081:80

networks:
  database:
    driver: bridge
    external: true
